name: Playwright UI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Start dev server
        run: |
          npm run dev &
          # wait for server to become available
          n=0; until curl -sS http://localhost:3003/ >/dev/null || [ $n -ge 30 ]; do n=$((n+1)); sleep 1; done
      - name: Run Playwright tests
        run: npx playwright test --config=test/playwright/playwright.config.ts
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: test/playwright/screenshots
      - name: Upload Playwright results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test/playwright/test-results || test-results
